# Generated by Django 4.1 on 2022-08-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0002_familia_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
