# Generated by Django 4.1 on 2022-08-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0003_alter_familia_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='genero',
            field=models.CharField(default='Some String', max_length=15),
        ),
        migrations.AddField(
            model_name='familia',
            name='relacion',
            field=models.CharField(default='Some String', max_length=40),
        ),
    ]
