# Generated by Django 4.1 on 2022-08-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0004_familia_genero_familia_relacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='genero',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='familia',
            name='relacion',
            field=models.CharField(max_length=40),
        ),
    ]
